---
- name: Fetch ibnbd sources
  git:
    repo: "{{ ibnbd_repo }}"
    dest: "{{ ibnbd_src }}"
    version: "{{ ibnbd_branch }}"
    depth: 1
    clone: true
    accept_hostkey: true

- name: ibnbd compilation
  shell:
    cmd: make KDIR="{{ kernel_src }}" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
    chdir: "{{ ibnbd_src }}"

- name: prepare kernel module directory
  file:
    mode: 0600
    owner: root
    state: directory
    path: "{{ rootfs_path }}/opt/modules"

- name: install kernel modules
  copy:
    src: "{{ item }}"
    dest: "{{ rootfs_path }}/opt/modules"
    owner: root
    mode: 0600
  loop:
    - "{{ ibnbd_src }}/rnbd/rnbd-client.ko"
    - "{{ ibnbd_src }}/rnbd/rnbd-server.ko"
    - "{{ ibnbd_src }}/rtrs/rtrs-core.ko"
    - "{{ ibnbd_src }}/rtrs/rtrs-client.ko"
    - "{{ ibnbd_src }}/rtrs/rtrs-server.ko"